### ISSUE TITLE
Control text on status bar

### ISSUE THREAD

**Issue by hyee** [cbucher/console#171]
Hi,

Is it possible to control the text of the status bar by setting environment variables, instead of the "ready" text. For example, timer, free text, etc. Thanks.

**Comment by hyee** [comment]
By the way, could anyone provide version 1.13?  I've tried download VS 2010 and failed for the compile. I only have very few knowledge on C++ and compiling.  Thanks.

**Comment by cbucher** [comment]
Hi,

Not it is not possible.

ConsoleZ only hooks the first process of the chain (the shell specified in the tab settings), so environment variables of other processes cannot be read.
That's the reason why I refuse communication by environment variables: I don't want a code that will work only in certain conditions (because I know that people don't read documentation and don't search in closed issues but they open an issue to ask why that don't work in this case? :wink:)

A second way to communicate with ConsoleZ will be an executable to call in scripts or a dedicated application. And I think a console application should not use GUI calls and must work without ConsoleZ.

A console is a big zone where you can display text so why do you want write in the status bar instead of the console?

Regards

**Comment by hyee** [comment]
Note with thanks
