### ISSUE TITLE
Record history of commands

### ISSUE THREAD

**Issue by tukanos** [cbucher/console#179]
It would be really useful if consoleZ would record a command history.  To list the history one would use up/down keys (could be also mappable) to scroll back and forth.  Complete history would be recorded into a file like e.g. bash does into .bash_history file.   It would be also nice to have settings to define how the size of the history recorded.

**Comment by cbucher** [comment]
duplicate #67
See documentation (Introduction: the first page):
NOTE: ConsoleZ is NOT a shell. Therefore, it does not implement shell features like command-line completion, syntax coloring, command history, etc.

**Comment by tukanos** [comment]
I tried to find any note, now after your comment I see it, next time I will search harder.

I understand that ConsoleZ is "only" very handy extension of the command line.  I don't see it as shell replacement, jus it is a program like any other.  For example, browsers, file managers, etc. also record their history and nobody is claiming thy try to replace shell.  History is very handy for daily usage and for me that is a key feature.  

Anyways, I'll try ConEmu to see how it compares.  Thank you for your efforts.

**Comment by cbucher** [comment]
**to clarify**

>For example, browsers, file managers, etc. also record their history and nobody is claiming they try to replace shell. History is very handy for daily usage and for me that is a key feature.

You want to store, in history, shell's commands you typed. (What else?)
How ConsoleZ (or any console wrapper) could understand what is a command?
If you store anything that is typed, you store commands, text inputs, passwords, ...
Imagine you launch a text editor (like vim) and ConsoleZ stores every key you pressed.

Assuming that we know we are in the prompt shell; we need to know the shell and its settings to interpret the command:
- We can write a character
- We can move (of a character, a line or a Word)
- We can insert text
- We can overwrite text
- We can delete text

That's why this should be done in the shell.

**Comment by tukanos** [comment]
I see.  Now I understand it.  The only option for a wrapper would be to store all written text after pressing enter, which could be an option, but you are right that not everybody would be satisfied with this solution.

Thank you for detailed explanation,  I think it will clear this question for others too.

**Comment by patricktokeeffe** [comment]
On the other hand, if the shell provides command history on it's own, shouldn't ConsoleZ support it implicitly? When I use `cmd.exe`, up/down keys provide command history but they do nothing when I talk to the windows command prompt through ConsoleZ. What could cause that - is there a layer missing (I mean is history provided by the cmd.exe GUI, not whatever ConsoleZ talks to)?

**Comment by cbucher** [comment]
No, I have already explained why...

**Comment by patricktokeeffe** [comment]
OK so it something different then. Thanks for clarifying.
