### ISSUE TITLE
Clearing screen option [enchancement]

### ISSUE THREAD

**Issue by cachaito** [cbucher/console#199]
Hi!

Would be possible to create 'clear screen' option in consoleZ like this in native bash `ctrl+l` style? I mean mostly to leave tilde-prefixes and not wipe out whole screen...

**Comment by cbucher** [comment]
Yes, you can. Go in `ConsoleZ Settings / Hotkeys` and search `Clear screen`.

**Comment by cachaito** [comment]
Hi Christophe, sorry I didn't explain my thoughts clearly - I know that there is an option Clear screen but it works like a wrote: it clears whole command window with tilda as well. In bash, when you use `ctrl+l` the tilda is always visible after clearing.

**Comment by cbucher** [comment]
What you want can only be done by sending a specific command to the shell (depending in the shell).

If your shell (like bash) allows hotkeys, configure it. Otherwise, you can use an external application like *autohotkey*.

Last solution: open a new feature request titled "*create keyboard macros*".

**Comment by cachaito** [comment]
Christophe I don't want to bother You.
> Last solution: open a new feature request titled "create keyboard macros".

Maybe You know if pyCmd or alternative (except Windows Goit Bash) has this feature?
