### ISSUE TITLE
File sub menu width

### ISSUE THREAD

**Issue by corvannoorloos** [cbucher/console#228]
Hello,

As I find the "File" sub menu rather huge compared to other sub menus, would it be possible to change the menu title to something simpler and similar to Sublime Text and Google Chrome?

Console:
![snag_program-0006](https://cloud.githubusercontent.com/assets/1499293/8143810/60e291aa-11bf-11e5-9609-5f4ece8653a9.png)

Sublime Text:
![snag_program-0008](https://cloud.githubusercontent.com/assets/1499293/8143811/60e3573e-11bf-11e5-8f0d-3c281a46a48e.png)

Also, what would be your opinion on having title case hotkeys (similar to Windows cmd.exe) instead of uppercase?

**Comment by cbucher** [comment]
>As I find the "File" sub menu rather huge compared to other sub menus, would it be possible to change the menu title to something simpler and similar to Sublime Text and Google Chrome?

No, it's nitpicking but I accept contributions...

`GetKeyNameText` API function is used to retrieve the hotkey name.
I display names that the API returns without modification.
For example in French I can have *CTRL+ENTREE (PAVE NUM.)*. If I convert in lowercase I will have *Ctrl+Entree (pave num.)*. That's wrong because diacritics are significant in French. I should have *Ctrl+Entrée (pavé num.)*!

>Also, what would be your opinion on having title case hotkeys (similar to Windows cmd.exe) instead of uppercase?

**Yes**, if you have source code that will be right in any language; otherwise **no**.
