### ISSUE TITLE
Customized color should respect the color of text that is not the default one

### ISSUE THREAD

**Issue by wayne-zhang** [cbucher/console#246]
When custom color is specified (Settings > Font > Custom color), text with special colors (which is not the default foreground color, for example, git shows files that are not added to stash zone as red) should be kept, but it was overwrote as the customised color as well.

Default color don't have this issue.

**Comment by wayne-zhang** [comment]
![consolez_default-color](https://cloud.githubusercontent.com/assets/3071035/8586791/90262ae2-2625-11e5-91de-f6e227625886.png)
![consolez_custom-color](https://cloud.githubusercontent.com/assets/3071035/8586794/981d2c78-2625-11e5-83c7-c78c695c6334.png)

**Comment by cbucher** [comment]
This is not an issue, this is the wanted behavior. Read the documentation.
If you want modify one color, modify the color in tab's settings.

**Comment by wayne-zhang** [comment]
On normal Windows Console, it is different. The color changed is just the text with default color, not the text with 'special' color. You may try it with Windows Console > Properties > Colors. See screen shot:

**Comment by wayne-zhang** [comment]
Windows CMD color change examples:
![administrator_color-1](https://cloud.githubusercontent.com/assets/3071035/8589581/6bef3e46-264a-11e5-9c32-8033e28e8a4a.png)
![administrator_color-2](https://cloud.githubusercontent.com/assets/3071035/8589580/6bef3b9e-264a-11e5-8a72-72bdac9d2b3a.png)

**Comment by wayne-zhang** [comment]
I am sure how Windows consoles coloring text (there is a tag/attribute on each text/line that have different colors?), but it is possible in technical point of view. Change color just change the default color, ignore the text that have special color attribute.

That is, change foreground color of the console should not make the console in a single color mode (only one foreground color), it should still be 'colorful'.

**Comment by wayne-zhang** [comment]
Is it possible to delegate set foreground color function to Windows CMD/Console?

**Comment by cbucher** [comment]
>I am sure how Windows consoles coloring text (there is a tag/attribute on each text/line that have different colors?)

In console buffer, each char has attributes (foreground color, background color, ...).
ConsoleZ don't know if a char is text, popup text or "special text"!

You can configure the index of screen text color with 
- the `color` command 
- or via Windows Console properties.
This configuration is used by the shell to format the output text.
ConsoleZ cannot determine what is the current index of screen text color nor if a char is screen text!

You can use the color command in shell command line. This is the simplest choice to have different screen colors per tab.
Otherwise, use `View / Console Window`to show the hidden console and you configure the properties as you usually do.
