### ISSUE TITLE
ClickLink() uses the same delimiters as SelectWord()

### ISSUE THREAD

**Issue by gfody** [cbucher/console#300]
The default word selection delimiters are sensible "([)]" but for links it means clicking on "https://en.wikipedia.org/wiki/Something_(Beatles_song)" will launch you to "https://en.wikipedia.org/wiki/Something_" - so we should maybe hard code different delimiters for ClickLink, perhaps just spaces and CRLFs?

As a feature request - it would be nice if the mouse cursor changed when hovering over a link so long as the shift key (or whatever) is held.

**Comment by cbucher** [comment]
1. there is no CRLF in screen buffer.
2. you can choose delimiters that match your needs (I know this is an easy answer :wink:)
3. link can be everything (not only an url) so you cannot define delimiters or regular expression... User must select separators that match their needs.
4. I could not code something good. So I made something easy... (the following text explain why)

I already think to display link with a regular expression.
But there are some problems:

You cannot search in ConsoleZ process: the buffer copied and returned to ConsoleZ contains only the visible chars. That's why I used the same code as SelectWord(). For example if you want to highlight email addresses, you have `bugs.bun`in the visible part and `ny@acme.corp` in the non visible part. The you must highlight `bugs.bun`in the visible part.

So you must search in ConsoleZ hook. 
You must read more than the visible part in console screen buffer.

If the search is ongoing, then you increase the risk of crash (see #279 there is no way to lock the console screen buffer; that is not thread safe and a reading during a console re-sizing is fatal! The PowerShell progress bar feature has been disabled for this reason and the code was simple!).

If the search is punctual (initiated by ConsoleZ process), then you must assume the text in returned coordinates will not change; otherwise you highlight something wrong. This is what is done with the search bar.
