### ISSUE TITLE
Git Bash tab causes "DLL injection has failed (reason:timeout (hook))!"

### ISSUE THREAD

**Issue by drewnoakes** [cbucher/console#301]
As part of #287 I downloaded beta version (ConsoleZ.x64.1.16.0.16029).

I tried wiring up Git Bash and when launching a new tab, it opens in a new window and a dialog appears with:

> DLL injection has failed (reason:timeout (hook))!

The path I used was `C:\Users\Drew\AppData\Local\Programs\Git\git-bash.exe`.

**Comment by drewnoakes** [comment]
Also, because I made this new Git Bash tab the default (moved it to the top) I can no longer launch the ConsoleZ main window in order to update settings. How can I reset the settings?

**Comment by cbucher** [comment]
git-bash.exe launches mintty.exe
git-bash.exe is not a Win32 console application
mintty.exe is not a Win32 console application

use "C:\Program Files\Git\usr\bin\sh.exe" and add environment varaibles
(see #273 git-cmd.exe are bugged and terminates when you press CTRL-C)

**Comment by drewnoakes** [comment]
Thanks.

However I can't start ConsoleZ with this configuration now. No UI appears, and I don't know where the settings are stored in order to delete/edit them manually.

**Comment by cbucher** [comment]
The configuration file location is documented in the [FAQ](https://github.com/cbucher/console/wiki/FAQ) section, or in the manual provided with ConsoleZ:

By default, your configuration file is located in `%APPDATA%\console` directory. Otherwise, it is located in the same directory as ConsoleZ program.
Rename it to reset configuration.
