### ISSUE TITLE
Virus Alert on ConsoleHook32.dll

### ISSUE THREAD

**Issue by karland** [cbucher/console#332]
@cbucher You are probably already aware of this. But because I could not find anything about virus alerts in this repository I am reporting it here in any case.

When I installed ConsoleZ I received a virus alert, reporting a threat called `Gen:Variant.Razy.25865`.

Please find more information here:

[Virus Alert](https://www.virustotal.com/en-gb/file/b7600ca4f98dcdd4cc06f98a03090c31a5a886594604aa760588f3459d6e79a2/analysis/)

**Comment by cbucher** [comment]
[Here](https://www.virustotal.com/en-gb/file/bf4e819b2b85cf1dc4e16848974c9d45c8f76dda4d43bb9533fcb222fb0cb64a/analysis/), the analysis of the same code built in 64 bit.

We can see some bad antivirus softwares:
- they detect false positives
- or they detect suspicious behavior (that's good) but only in 32 bits ... so you're not protected in 64 bits! (that's bad)

I am not surprised that an antivirus software throws an alert with ConsoleZ because it uses DLL injection. I can do nothing. That's an open source project: people can read the code and build the application by themselves.
