### ISSUE TITLE
Allow the user to override the automatic language selection

### ISSUE THREAD

**Issue by BhaaLseN** [cbucher/console#334]
#303 is a nice step towards non-native english speakers and provides them with a localized UI in their own native language (given the localization exists). However, not everyone wants that; and I'm one of those guys.
For the lack of a language selection (that, for example, contains Options such as "Automatic (OS Language)" and "English"/"German"/"French"/"Russian") I had to rename `console_DEU.dll` to get the english UI back.

This is certainly not a high priority feature request, but I'd appreciate it being considered for a future version :)

**Comment by cbucher** [comment]
>However, not everyone wants that; and I'm one of those guys.

So why don't configure your Windows profile with english language?
I prefer english UI too, that's why I choose english language in Windows settings.
For consistency, I want to see same language in all my applications.

>For the lack of a language selection (that, for example, contains Options such as "Automatic (OS Language)" and "English"/"German"/"French"/"Russian") I had to rename console_DEU.dll to get the english UI back.

There is no lack of language selection, the user profile language is used. 
Localized files are optional, you can delete them.

**Comment by BhaaLseN** [comment]
If this should be the intended way of selecting the language, fine by me - but I suggest at least adding an entry to the [FAQ](https://github.com/cbucher/console/wiki/FAQ) about it. Not everyone thinks it could be intended to _delete_ files intentionally for something like that.

**Comment by cbucher** [comment]
done
