### ISSUE TITLE
TCC/LE 64-bit Crashes on Loading / Attaching

### ISSUE THREAD

**Issue by alexgieg** [cbucher/console#354]
### Expected Behavior

Open a TCC/LE 64-bit tab in ConsoleZ 64-bit and have it working.
### Actual Behavior

Opening a TCC/LE 64-bit tab from within ConsoleZ, or trying to attach a running one, causes a crash followed by a DLL injection error:
#### a) When launching directly:

![czss01](https://cloud.githubusercontent.com/assets/1074619/16917844/abb3cf72-4cd9-11e6-85db-a5a145b4fad5.png)
![czss02](https://cloud.githubusercontent.com/assets/1074619/16917871/c7e2d512-4cd9-11e6-8fd8-25c1e7f1adbb.png)
![czss03](https://cloud.githubusercontent.com/assets/1074619/16917878/cc6c64fe-4cd9-11e6-88c7-5bbbb5aecc30.png)
![czss04](https://cloud.githubusercontent.com/assets/1074619/16917893/d500c90c-4cd9-11e6-9223-6df42948fbb4.png)
#### b) When attaching an existing console:

![czss05](https://cloud.githubusercontent.com/assets/1074619/16917900/da90a298-4cd9-11e6-9758-d221ddd23380.png)
![czss06](https://cloud.githubusercontent.com/assets/1074619/16917902/df461962-4cd9-11e6-9d61-0f5cffbfa19a.png)
![czss04](https://cloud.githubusercontent.com/assets/1074619/16917893/d500c90c-4cd9-11e6-9223-6df42948fbb4.png)
### Steps to reproduce
1. Download and install TCC/LE 64-bit from [JPSoft's Website](https://jpsoft.com/all-downloads/downloads.html).
2. Create a tab entry pointing to the TCC/LE 64-bit executable (screenshot below).
3. Launch it.

![czss07](https://cloud.githubusercontent.com/assets/1074619/16918059/7c8678a2-4cda-11e6-8ad5-f8db5431580e.png)
### Diagnostic Report
- Report: [czss08.txt](https://github.com/cbucher/console/files/369282/czss08.txt)
### Crash Report
- Direct loading: [czss09.zip](https://github.com/cbucher/console/files/369291/czss09.zip)
- Attaching: [czss10.zip](https://github.com/cbucher/console/files/369295/czss10.zip)

**Comment by cbucher** [comment]
*tcc.exe* has been compiled with large address support disabled.

```
>dumpbin /HEADERS "C:\Program Files\JPSoft\TCCLE14x64\tcc.exe"
Microsoft (R) COFF/PE Dumper Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Program Files\JPSoft\TCCLE14x64\tcc.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               5 number of sections
        56B611A2 time date stamp Sat Feb 06 16:30:42 2016
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
               3 characteristics
                   Relocations stripped
                   Executable
```

DLL injection requires guessing the address of LoadLibraryW function in the target process. We assume ConsoleZ and target process loads kernel32 module in the same address space.
This assumption is correct because ntdll and kernel32 are always loaded in the same order for each process.
But if 64 bits process is not large address aware, then modules will be loaded at different addresses (under 2 GB).

You can modify the flag with EditBin.exe:
`>EditBin /LARGEADDRESSAWARE "C:\temp\tcc.exe"`

After modification, the DLL injection will be a success.

```
>dumpbin /HEADERS "C:\temp\tcc.exe"
Microsoft (R) COFF/PE Dumper Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\temp\tcc.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               5 number of sections
        56B611A2 time date stamp Sat Feb 06 16:30:42 2016
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
              23 characteristics
                   Relocations stripped
                   Executable
                   Application can handle large (>2GB) addresses
```

Note: **editbin.exe** and **dumpbin.exe** are parts of Visual Studio. If you don't want install Visual Studio you use another tools.

With CFF Explorer (http://www.ntcore.com/exsuite.php):
![image](https://cloud.githubusercontent.com/assets/363759/16951273/8f0c180c-4dc4-11e6-95c5-659a80e45154.png)

**Comment by alexgieg** [comment]
Thank you very much! I'll file a bug report with JPSoft asking them to enable large address support in the next update.
