### ISSUE TITLE
Reset shell

### ISSUE THREAD

**Issue by dashesy** [cbucher/console#355]
I am trying to use the shell from Git-Bash in ConsoleZ.
I tried this:
```sh
    "C:\Program Files\Git\bin\bash.exe -i --login"
```

It did not work. But the main problem is that now I cannot run `Console.exe` anymore and I get this error:

```text
    Unable to start "C:\Program Files\Git\bin\bash.exe -i --login" (reason: (CreateProcess) The system cannot find the file specified.)!
```

I am now looking into the registry to change that value so that I can run `Console.exe` again and try other options. If the shell is not found perhaps the safest option is to try the default shell, so that users can try other options.

**Comment by cbucher** [comment]
Correct your command line.
Try `"C:\Program Files\Git\bin\bash.exe" -i --login`

**Comment by sourav2029** [comment]
I am trying to use powershell in consolez . I tried 
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\System Tools\Windows PowerShell.lnk" in the shell option in the tabs setting menu .Now i am unable to start consolez and the reason is (CreateProcess).  I do i undo this and how can i use powershell in consolez.. 

I have not installed consolez using Chocolatey . I simply downloaded the zip . Plz help me

**Comment by cbucher** [comment]
Install last beta version (see downlad section in wiki).
ConsoleZ will start in fail mode.
And then fix your settings. You just have to drag and drop the link from the start menu into the shell text area (tabs settings).

Verify that your settings are correct before exiting by launching one time the tab modified. Set a tab as default (first place in settings) only after testing.

**Comment by sourav2029** [comment]
@cbucher Thanks for the reply but that does not work for me ..i downloaded the beta version but i m still getting the same error ..is there any other way to reset the setting

**Comment by dashesy** [comment]
I stopped using it because there was no way to reset the setting and this bug was closed so I thought it will never be fixed.

**Comment by cbucher** [comment]
The error will not disappear until you fixed your configuration. Beta version allow ConsoleZ application to start in safe mode and access to settings (and then you can fix from settings menu).

If ConsoleZ doesn't start in safe mode:
- you have modified your COMSPEC environment variable by something wrong
- you haven't launched the beta version of ConsoleZ

Otherwise you can remove or edit the configuration file (see FAQ in wiki).

**Comment by sourav2029** [comment]
@dashesy  thank you editing the console.xml worked for me and the error was because i was directly copy ing and pasting the file location from my start menu in the shell option . Also what does this -i --login option does? I just wanted to know
