### ISSUE TITLE
it is necessary different cursor shape in insert mode and overwrite mode

### ISSUE THREAD

**Issue by khasco** [cbucher/console#467]
Hello Dear

at first very thank for writing consolez

1) it is necessary different cursor size in insert mode and overwrite mode same as cmd.exe console, please add ability to define cursor size (for example from 1 to 4) for insert mode and overwrite mode in tabs menu>colors & cursor (it is best way to customize cursor size)

![01](https://user-images.githubusercontent.com/37120866/37055985-51d5029c-2198-11e8-9fc5-e9c07e4c77a0.jpg)

2) how can i disable ALT key for not showing consolez menu? because in my application ALT key is for activating its menu too

3) how can i create shortcut to running batch file (my.bat) with consolez (not with cmd.exe)?

Thanks

**Comment by cbucher** [comment]
Hello,

1.
There is no way to know if you are in insert mode or overwrite mode.
Insert/Overwrite mode is managed by the shell/application. There is no Win32 console function to get this information.
So that is not possible.

2.
You cannot disable ALT key for not showing ConsoleZ menu.
If menu is visible (checked in Menu/View), do you receive ALT key in your application ?

3.
To launch a cmd in ConsoleZ, use **-r** argument.
For example: `console.exe -r "/C test.cmd"`
See ConsoleZ documentation and `cmd.exe /?` to find the command line corresponding to your settings.

To associate cmd files with ConsoleZ, you can modify registry:
HKEY_CLASSES_ROOT\cmdfile\shell\runas\command
**But I strongly recommend to not modify the association.**
Planified/hidden tasks will stop working.
Calling a cmd file from ConsoleZ will create a new instance of ConsoleZ or a new tab...

Regards

**Comment by khasco** [comment]
Hello Dear cbucher

Thank you for replying

your answer for number 3 was very useful and i could create my shortcut for running my batch file under consolez with format: console.exe -r "/C myapp.bat", thank again

i have another question please answer it too

4) i use consolez for running my foxprox application (16 bit ms-dos application) under windows 32 bit, can i use consolez for running my application under windows 64 bit? at present i use dosbox for running my application under windows 64 bit but it has some limitations

Best Regards

**Comment by cbucher** [comment]
You cannot execute 16 bits applications on Windows 64 bits.
Microsoft provides a
- 16 bits "compatibility" on Windows 32 bits (WOW aka Windows on Windows).
- 32 bits "compatibility" on Windows 64 bits (WOW64 aka Windows on Windows 64).

You have to emulate x86 processor to run 16 bis applications on Windows 64 (using dosbox).
ConsoleZ wraps Windows console applications (using WIN32 console API), so you need a Windows console application which emulate 16 bits x86 and dos.
I found this: https://sourceforge.net/projects/nxvdm/
Does it help you?

**Comment by khasco** [comment]
Hello Dear

thank you for helping for nxvdm, i saw that page but unfortunately there is not any exe or com file to run nxvm

**Comment by cbucher** [comment]
>you said that "There is no way to know if you are in insert mode or overwrite mode.", but is it possible to define default size of cursor in consolez (that at present, it is same as large size of cursor in cmd.exe) same as medium size (or small size) in cmd.exe,

If you want to mimic Windows console cursor, choose cursor named "console" in tabs settings. This cursor uses the size defined in Windows console properties.

>you said that "i cannot disable ALT key for not showing Consolez menu." but is it possible to define ALT key or any other key (for example F12 key) for activating consolez menu?

No, it is not possible to define another key.
