### ISSUE TITLE
8-bit Color Support

### ISSUE THREAD

**Issue by Alexander-Shukaev** [cbucher/console#57]
Do you plan to add 8-bit color support? I think this is the killer feature that would be really nice to have. For example, for those of us who use Vim or Emacs, it's really annoying to work with just 4-bit color. Anyway, thanks for your efforts, you're doing great job!

**Comment by mikofski** [comment]
Hi @cbucher thank you so much for this windows console emulator! Your contribution is very much appreciated!

The limitation in colors is unfortunately an issue because more applications, such as python-pip and python-sphinx, are using more colors which in Console2 and ConsoleZ get translated to color codes in text (see below: `?[33m` and `?[K`) which are distracting and confusing.

I know you have closed this issue, and said that it is a choice, but I think ConsoleZ would be a more attractive alternative if it were able to emulate these colors, even if it were only to remove the undesirable symbols from `STDOUT`.

Thanks for your consideration!

Example:

    $ pip install -U South
    ?[33mYou are using pip version 7.1.0, however version 7.1.2 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.?[0m
    Collecting South
    C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
      Downloading South-1.0.2.tar.gz (96kB)
    ?[K    100% |################################| 98kB 650kB/s ta 0:00:01
    Building wheels for collected packages: South
      Running setup.py bdist_wheel for South
      Stored in directory: ~\AppData\Local\pip\Cache\wheels\11\2b\ca\a57966e1943759859dd94f3ebc5c279450bee11e07d600e3a3
    Successfully built South
    Installing collected packages: South
    Successfully installed South-1.0.2

**Comment by cbucher** [comment]
HI @mikofski 

Use ConsoleZ with ANSICON to translate ANSI Escape sequences.

The only problem discussed here is 8 bits colors support.

ConsoleZ is a **Windows console** wrapper. Windows console doesn't support 8 bits colors, so ANSICON doesn't support 8 bits colors.

**Comment by mikofski** [comment]
Thanks!

**Comment by pianocomposer321** [comment]
Windows cmd has 24-bit colors now, but consolez still doesn't even have 8-bit, as far as I can tell. Is there a reason for this?
